
CREATE TABLE IF NOT EXISTS theme
(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE user
    ADD theme_id INT NULL AFTER enabled,
    ADD FOREIGN KEY (theme_id) REFERENCES user(id);