name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploy-documentation"
  cancel-in-progress: true

jobs:
  build:
    name: Upload documentation
    runs-on: ubuntu-latest
    container: swift:5.9.2-jammy
    steps:
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

